### ISSUE TITLE
Fatal error in crud/create

### ISSUE THREAD

**Issue by yesaulov** [vegas-cmf/demo#6]
Hi!
1. Clone repo, composer install and run. 
2. Create user and login.
   Everything is ok.
   Then try to create crud entry and after submit form see:

```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /vagrant/test/vendor/vegas-cmf/core/src/DI/Scaffolding.php on line 203
```

hm, line with

```
if ($form->isValid()) {
```

**Comment by arius86** [comment]
What version of Phalcon are you using, what OS and it is apache or nginx?

**Comment by yesaulov** [comment]
@arius86 phalcon 1.3.4, and nginx 1.1.9

**Comment by arius86** [comment]
@yesaulov I will check this ASAP, meanwhile please install https://github.com/vegas-cmf/official instead of demo. Should be working :)

**Comment by arius86** [comment]
@yesaulov I checked demo project on the same configuration, using artcile CRUD, and everything looks fine. Try to install demo by https://github.com/vegas-cmf/vegaser - if the same error will occur it will be propably an issue with nginx configuration.  Check "getting started" part in out docs for more details: http://vegas-cmf.github.io/1.1/getting-started.html

**Comment by yesaulov** [comment]
@arius86 Thanks, with official version everything is ok.

**Comment by bartpie** [comment]
I had the same problem in **phalcon 1.3.4** and **apache** at last I use `grep -r 'phalcon' /etc/php5/` and I found twice included extension **phalcon.os**. 
I removed duplicated including and it helped.
https://github.com/phalcon/cphalcon/issues/2434#issuecomment-44264089

> Fatal error: Maximum function nesting level of '100' reached, aborting! in /vagrant/test/vendor/vegas-cmf/core/src/DI/Scaffolding.php on line 203
